class Weather
  attr_reader :zip_code
  attr_reader :location

  def initialize(zip_code = "34102")
     @zip_code = zip_code
     @location ||= get_pretty_local_weather
  end

  private

  def api_call
    @w_api ||= Wunderground.new(ENV["WUG_CREDS"])
  end

  def local_weather
    api_call.conditions_for(@zip_code)
  end

  def get_pretty_local_weather
    # local_weather["current_observation"]
    if @zip_code == "34102"
      {"image"=>{"url"=>"http://icons.wxug.com/graphics/wu2/logo_130x80.png", "title"=>"Weather Underground", "link"=>"http://www.wunderground.com"}, "display_location"=>{"full"=>"Naples, FL", "city"=>"Naples", "state"=>"FL", "state_name"=>"Florida", "country"=>"US", "country_iso3166"=>"US", "zip"=>"34102", "magic"=>"1", "wmo"=>"99999", "latitude"=>"26.14016914", "longitude"=>"-81.79814911", "elevation"=>"9.00000000"}, "observation_location"=>{"full"=>"Naples, Florida", "city"=>"Naples", "state"=>"Florida", "country"=>"US", "country_iso3166"=>"US", "latitude"=>"26.157749", "longitude"=>"-81.778618", "elevation"=>"20 ft"}, "estimated"=>{}, "station_id"=>"KFLNAPLE31", "observation_time"=>"Last Updated on July 2, 5:49 PM EDT", "observation_time_rfc822"=>"Thu, 02 Jul 2015 17:49:13 -0400", "observation_epoch"=>"1435873753", "local_time_rfc822"=>"Thu, 02 Jul 2015 17:59:33 -0400", "local_epoch"=>"1435874373", "local_tz_short"=>"EDT", "local_tz_long"=>"America/New_York", "local_tz_offset"=>"-0400", "weather"=>"Partly Cloudy", "temperature_string"=>"77.1 F (25.1 C)", "temp_f"=>77.1, "temp_c"=>25.1, "relative_humidity"=>"84%", "wind_string"=>"From the North at 7.0 MPH Gusting to 10.0 MPH", "wind_dir"=>"North", "wind_degrees"=>355, "wind_mph"=>7.0, "wind_gust_mph"=>"10.0", "wind_kph"=>11.3, "wind_gust_kph"=>"16.1", "pressure_mb"=>"1018", "pressure_in"=>"30.05", "pressure_trend"=>"+", "dewpoint_string"=>"72 F (22 C)", "dewpoint_f"=>72, "dewpoint_c"=>22, "heat_index_string"=>"NA", "heat_index_f"=>"NA", "heat_index_c"=>"NA", "windchill_string"=>"NA", "windchill_f"=>"NA", "windchill_c"=>"NA", "feelslike_string"=>"77.1 F (26 C)", "feelslike_f"=>"77.1", "feelslike_c"=>"26", "visibility_mi"=>"10.0", "visibility_km"=>"16.1", "solarradiation"=>"--", "UV"=>"4", "precip_1hr_string"=>"0.10 in ( 3 mm)", "precip_1hr_in"=>"0.10", "precip_1hr_metric"=>" 3", "precip_today_string"=>"0.20 in (5 mm)", "precip_today_in"=>"0.20", "precip_today_metric"=>"5", "icon"=>"partlycloudy", "icon_url"=>"http://icons.wxug.com/i/c/k/partlycloudy.gif", "forecast_url"=>"http://www.wunderground.com/US/FL/Naples.html", "history_url"=>"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KFLNAPLE31", "ob_url"=>"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=26.157749,-81.778618", "nowcast"=>" Scattered showers and thunderstorms will affect interior\nSouth Florida and eventually the Gulf Coast as evening\napproaches. The main impact from the thunderstorms will be lightning\nstrikes. There is the potential for a few strong storms to\ndevelop with strong wind gusts possible. Mariners should be alert\nfor rapidly changing conditions. Remember that lightning can\nstrike over 10 miles away from thunderstorms."}
    elsif @zip_code == "02135"
      {"image"=>{"url"=>"http://icons.wxug.com/graphics/wu2/logo_130x80.png", "title"=>"Weather Underground", "link"=>"http://www.wunderground.com"}, "display_location"=>{"full"=>"Brighton, MA", "city"=>"Brighton", "state"=>"MA", "state_name"=>"Mass", "country"=>"US", "country_iso3166"=>"US", "zip"=>"02135", "magic"=>"1", "wmo"=>"99999", "latitude"=>"26.14016914", "longitude"=>"-81.79814911", "elevation"=>"9.00000000"}, "observation_location"=>{"full"=>"Naples, Florida", "city"=>"Naples", "state"=>"Florida", "country"=>"US", "country_iso3166"=>"US", "latitude"=>"26.157749", "longitude"=>"-81.778618", "elevation"=>"20 ft"}, "estimated"=>{}, "station_id"=>"KFLNAPLE31", "observation_time"=>"Last Updated on July 2, 5:49 PM EDT", "observation_time_rfc822"=>"Thu, 02 Jul 2015 17:49:13 -0400", "observation_epoch"=>"1435873753", "local_time_rfc822"=>"Thu, 02 Jul 2015 17:59:33 -0400", "local_epoch"=>"1435874373", "local_tz_short"=>"EDT", "local_tz_long"=>"America/New_York", "local_tz_offset"=>"-0400", "weather"=>"Partly Cloudy", "temperature_string"=>"77.1 F (25.1 C)", "temp_f"=>50.1, "temp_c"=>12.2, "relative_humidity"=>"84%", "wind_string"=>"From the North at 7.0 MPH Gusting to 10.0 MPH", "wind_dir"=>"North", "wind_degrees"=>355, "wind_mph"=>7.0, "wind_gust_mph"=>"10.0", "wind_kph"=>11.3, "wind_gust_kph"=>"16.1", "pressure_mb"=>"1018", "pressure_in"=>"30.05", "pressure_trend"=>"+", "dewpoint_string"=>"72 F (22 C)", "dewpoint_f"=>72, "dewpoint_c"=>22, "heat_index_string"=>"NA", "heat_index_f"=>"NA", "heat_index_c"=>"NA", "windchill_string"=>"NA", "windchill_f"=>"NA", "windchill_c"=>"NA", "feelslike_string"=>"77.1 F (26 C)", "feelslike_f"=>"77.1", "feelslike_c"=>"26", "visibility_mi"=>"10.0", "visibility_km"=>"16.1", "solarradiation"=>"--", "UV"=>"4", "precip_1hr_string"=>"0.10 in ( 3 mm)", "precip_1hr_in"=>"0.10", "precip_1hr_metric"=>" 3", "precip_today_string"=>"0.20 in (5 mm)", "precip_today_in"=>"0.20", "precip_today_metric"=>"5", "icon"=>"partlycloudy", "icon_url"=>"http://icons.wxug.com/i/c/k/partlycloudy.gif", "forecast_url"=>"http://www.wunderground.com/US/FL/Naples.html", "history_url"=>"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KFLNAPLE31", "ob_url"=>"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=26.157749,-81.778618", "nowcast"=>" Scattered showers and thunderstorms will affect interior\nSouth Florida and eventually the Gulf Coast as evening\napproaches. The main impact from the thunderstorms will be lightning\nstrikes. There is the potential for a few strong storms to\ndevelop with strong wind gusts possible. Mariners should be alert\nfor rapidly changing conditions. Remember that lightning can\nstrike over 10 miles away from thunderstorms."}
    else
      {"image"=>{"url"=>"http://icons.wxug.com/graphics/wu2/logo_130x80.png", "title"=>"Weather Underground", "link"=>"http://www.wunderground.com"}, "display_location"=>{"full"=>"Custom, Place", "city"=>"Somewhere", "state"=>"XX", "state_name"=>"Anywhere", "country"=>"US", "country_iso3166"=>"US", "zip"=>"02135", "magic"=>"1", "wmo"=>"99999", "latitude"=>"26.14016914", "longitude"=>"-81.79814911", "elevation"=>"9.00000000"}, "observation_location"=>{"full"=>"Naples, Florida", "city"=>"Naples", "state"=>"Florida", "country"=>"US", "country_iso3166"=>"US", "latitude"=>"26.157749", "longitude"=>"-81.778618", "elevation"=>"20 ft"}, "estimated"=>{}, "station_id"=>"KFLNAPLE31", "observation_time"=>"Last Updated on July 2, 5:49 PM EDT", "observation_time_rfc822"=>"Thu, 02 Jul 2015 17:49:13 -0400", "observation_epoch"=>"1435873753", "local_time_rfc822"=>"Thu, 02 Jul 2015 17:59:33 -0400", "local_epoch"=>"1435874373", "local_tz_short"=>"EDT", "local_tz_long"=>"America/New_York", "local_tz_offset"=>"-0400", "weather"=>"Partly Cloudy", "temperature_string"=>"77.1 F (25.1 C)", "temp_f"=>100.1, "temp_c"=>55.9, "relative_humidity"=>"84%", "wind_string"=>"From the North at 7.0 MPH Gusting to 10.0 MPH", "wind_dir"=>"North", "wind_degrees"=>355, "wind_mph"=>7.0, "wind_gust_mph"=>"10.0", "wind_kph"=>11.3, "wind_gust_kph"=>"16.1", "pressure_mb"=>"1018", "pressure_in"=>"30.05", "pressure_trend"=>"+", "dewpoint_string"=>"72 F (22 C)", "dewpoint_f"=>72, "dewpoint_c"=>22, "heat_index_string"=>"NA", "heat_index_f"=>"NA", "heat_index_c"=>"NA", "windchill_string"=>"NA", "windchill_f"=>"NA", "windchill_c"=>"NA", "feelslike_string"=>"77.1 F (26 C)", "feelslike_f"=>"77.1", "feelslike_c"=>"26", "visibility_mi"=>"10.0", "visibility_km"=>"16.1", "solarradiation"=>"--", "UV"=>"4", "precip_1hr_string"=>"0.10 in ( 3 mm)", "precip_1hr_in"=>"0.10", "precip_1hr_metric"=>" 3", "precip_today_string"=>"0.20 in (5 mm)", "precip_today_in"=>"0.20", "precip_today_metric"=>"5", "icon"=>"partlycloudy", "icon_url"=>"http://icons.wxug.com/i/c/k/partlycloudy.gif", "forecast_url"=>"http://www.wunderground.com/US/FL/Naples.html", "history_url"=>"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KFLNAPLE31", "ob_url"=>"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=26.157749,-81.778618", "nowcast"=>" Scattered showers and thunderstorms will affect interior\nSouth Florida and eventually the Gulf Coast as evening\napproaches. The main impact from the thunderstorms will be lightning\nstrikes. There is the potential for a few strong storms to\ndevelop with strong wind gusts possible. Mariners should be alert\nfor rapidly changing conditions. Remember that lightning can\nstrike over 10 miles away from thunderstorms."}
    end
  end

end
